Fix token fetch, director creation in plan-patch
- Fixes race in terraform data provider when fetching a token for a
service account on the Kubernetes cluster
- Actually executes the create-director script

fixes:
```
Error: Error running plan: 1 error(s) occurred:

* output.k8s_service_token: Resource
'data.kubernetes_secret.k8s_service_token' does not have attribute
'data.token' for variable
'data.kubernetes_secret.k8s_service_token.data.token'
```